runtime: nodejs10

instance_class: F2

env_variables:
  HOST: 'apswedo-api.appspot.com'
  NODE_ENV: 'production'
  DATABASE_NAME: 'postgres'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'GKAgK544MbsJAeGJ'
  INSTANCE_CONNECTION_NAME: 'apswedo-api:us-east1:apswedo'

beta_settings:
  cloud_sql_instances: '<instance_identifier>'